# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cala

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cala

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cala/CMakeFiles /home/cala//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cala/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tm

# Build rule for target.
tm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tm
.PHONY : tm

# fast build rule for target.
tm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/build
.PHONY : tm/fast

#=============================================================================
# Target rules for targets named th

# Build rule for target.
th: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 th
.PHONY : th

# fast build rule for target.
th/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/build
.PHONY : th/fast

#=============================================================================
# Target rules for targets named sc

# Build rule for target.
sc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sc
.PHONY : sc

# fast build rule for target.
sc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/build
.PHONY : sc/fast

commands.o: commands.c.o
.PHONY : commands.o

# target to build an object file
commands.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/commands.c.o
.PHONY : commands.c.o

commands.i: commands.c.i
.PHONY : commands.i

# target to preprocess a source file
commands.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/commands.c.i
.PHONY : commands.c.i

commands.s: commands.c.s
.PHONY : commands.s

# target to generate assembly for a file
commands.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/commands.c.s
.PHONY : commands.c.s

common.o: common.c.o
.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i
.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s
.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/common.c.s
.PHONY : common.c.s

handle_signals.o: handle_signals.c.o
.PHONY : handle_signals.o

# target to build an object file
handle_signals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/handle_signals.c.o
.PHONY : handle_signals.c.o

handle_signals.i: handle_signals.c.i
.PHONY : handle_signals.i

# target to preprocess a source file
handle_signals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/handle_signals.c.i
.PHONY : handle_signals.c.i

handle_signals.s: handle_signals.c.s
.PHONY : handle_signals.s

# target to generate assembly for a file
handle_signals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/handle_signals.c.s
.PHONY : handle_signals.c.s

hub_commands.o: hub_commands.c.o
.PHONY : hub_commands.o

# target to build an object file
hub_commands.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/hub_commands.c.o
.PHONY : hub_commands.c.o

hub_commands.i: hub_commands.c.i
.PHONY : hub_commands.i

# target to preprocess a source file
hub_commands.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/hub_commands.c.i
.PHONY : hub_commands.c.i

hub_commands.s: hub_commands.c.s
.PHONY : hub_commands.s

# target to generate assembly for a file
hub_commands.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/hub_commands.c.s
.PHONY : hub_commands.c.s

interface.o: interface.c.o
.PHONY : interface.o

# target to build an object file
interface.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/interface.c.o
.PHONY : interface.c.o

interface.i: interface.c.i
.PHONY : interface.i

# target to preprocess a source file
interface.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/interface.c.i
.PHONY : interface.c.i

interface.s: interface.c.s
.PHONY : interface.s

# target to generate assembly for a file
interface.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/interface.c.s
.PHONY : interface.c.s

score_calculator.o: score_calculator.c.o
.PHONY : score_calculator.o

# target to build an object file
score_calculator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/score_calculator.c.o
.PHONY : score_calculator.c.o

score_calculator.i: score_calculator.c.i
.PHONY : score_calculator.i

# target to preprocess a source file
score_calculator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/score_calculator.c.i
.PHONY : score_calculator.c.i

score_calculator.s: score_calculator.c.s
.PHONY : score_calculator.s

# target to generate assembly for a file
score_calculator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sc.dir/build.make CMakeFiles/sc.dir/score_calculator.c.s
.PHONY : score_calculator.c.s

treasure_hub.o: treasure_hub.c.o
.PHONY : treasure_hub.o

# target to build an object file
treasure_hub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/treasure_hub.c.o
.PHONY : treasure_hub.c.o

treasure_hub.i: treasure_hub.c.i
.PHONY : treasure_hub.i

# target to preprocess a source file
treasure_hub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/treasure_hub.c.i
.PHONY : treasure_hub.c.i

treasure_hub.s: treasure_hub.c.s
.PHONY : treasure_hub.s

# target to generate assembly for a file
treasure_hub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/th.dir/build.make CMakeFiles/th.dir/treasure_hub.c.s
.PHONY : treasure_hub.c.s

treasure_manager.o: treasure_manager.c.o
.PHONY : treasure_manager.o

# target to build an object file
treasure_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/treasure_manager.c.o
.PHONY : treasure_manager.c.o

treasure_manager.i: treasure_manager.c.i
.PHONY : treasure_manager.i

# target to preprocess a source file
treasure_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/treasure_manager.c.i
.PHONY : treasure_manager.c.i

treasure_manager.s: treasure_manager.c.s
.PHONY : treasure_manager.s

# target to generate assembly for a file
treasure_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tm.dir/build.make CMakeFiles/tm.dir/treasure_manager.c.s
.PHONY : treasure_manager.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sc"
	@echo "... th"
	@echo "... tm"
	@echo "... commands.o"
	@echo "... commands.i"
	@echo "... commands.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... handle_signals.o"
	@echo "... handle_signals.i"
	@echo "... handle_signals.s"
	@echo "... hub_commands.o"
	@echo "... hub_commands.i"
	@echo "... hub_commands.s"
	@echo "... interface.o"
	@echo "... interface.i"
	@echo "... interface.s"
	@echo "... score_calculator.o"
	@echo "... score_calculator.i"
	@echo "... score_calculator.s"
	@echo "... treasure_hub.o"
	@echo "... treasure_hub.i"
	@echo "... treasure_hub.s"
	@echo "... treasure_manager.o"
	@echo "... treasure_manager.i"
	@echo "... treasure_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

